name: mobile_scanner
description: A universal barcode and QR code scanner for Flutter based on MLKit. Uses CameraX on Android, AVFoundation on iOS and Apple Vision & AVFoundation on macOS.
version: 6.0.0
repository: https://github.com/juliansteenbakker/mobile_scanner

screenshots:
- description: 'Flutter Demo Home Page'
  path: example/screenshots/homepage.png
- description: 'Mobile Scanner with controller'
  path: example/screenshots/controller.png
- description: 'Mobile Scanner with controller (returning image)'
  path: example/screenshots/returningImage.png
- description: 'Mobile Scanner with zoom slider'
  path: example/screenshots/zoomSlider.png
- description: 'Mobile Scanner with overlay'
  path: example/screenshots/overlay.png

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  web: ">=0.5.1 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ">=1.10.0 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.steenbakker.mobile_scanner
        pluginClass: MobileScannerPlugin
      ios:
        pluginClass: MobileScannerPlugin
      macos:
        pluginClass: MobileScannerPlugin
      web:
        pluginClass: MobileScannerWeb
        fileName: src/web/mobile_scanner_web.dart
