name: mobile_scanner
description: A universal barcode and QR code scanner for Flutter based on MLKit. Uses CameraX on Android, AVFoundation on iOS and Apple Vision & AVFoundation on macOS.
version: 3.2.0
repository: https://github.com/juliansteenbakker/mobile_scanner

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ">=1.10.0 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.steenbakker.mobile_scanner
        pluginClass: MobileScannerPlugin
      ios:
        pluginClass: MobileScannerPlugin
      macos:
        pluginClass: MobileScannerPlugin
      web:
        pluginClass: MobileScannerWebPlugin
        fileName: mobile_scanner_web_plugin.dart